import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { commitWorktree, createWorktree, mergeWorktree, removeWorktree } from "../src/worktree.js";

// Set up a temp git repo with one initial commit (file.txt = "base\n") so a
// worktree can be branched off HEAD. Returns the repo path plus helpers that run
// git against it (`git` for mutations, `gitOut` for reading command output).
function setupRepo(prefix: string): {
  repo: string;
  git: (...args: string[]) => void;
  gitOut: (...args: string[]) => string;
} {
  const repo = mkdtempSync(join(tmpdir(), prefix));
  const git = (...args: string[]) => {
    execFileSync("git", ["-C", repo, ...args], { stdio: "pipe" });
  };
  const gitOut = (...args: string[]) => execFileSync("git", ["-C", repo, ...args], { encoding: "utf8" });
  git("init", "-q");
  git("config", "user.email", "t@t.t");
  git("config", "user.name", "t");
  writeFileSync(join(repo, "file.txt"), "base\n");
  git("add", ".");
  git("commit", "-q", "-m", "init");
  return { repo, git, gitOut };
}

test("commitWorktree + mergeWorktree lands worktree edits on the base branch", async () => {
  const { repo, gitOut } = setupRepo("pi-saga-happy-");
  try {
    const wt = await createWorktree(repo, "run-1-0-feature");
    assert.equal(wt.isolated, true);

    // A brand-new file only the isolated agent created.
    writeFileSync(join(wt.cwd, "feature.txt"), "generated by agent\n");
    assert.ok(!existsSync(join(repo, "feature.txt")), "base tree untouched before merge");

    const committed = await commitWorktree(wt, "pi/wf feature");
    assert.equal(committed, true, "commit made on the branch");
    // Commit stays on the branch until merged — base still has no feature.txt.
    assert.ok(!existsSync(join(repo, "feature.txt")), "commit alone does not touch base");

    const result = await mergeWorktree(wt);
    assert.deepEqual(result, { merged: true, conflict: false });

    // The saga's whole point: the file now exists on the base branch at repoRoot.
    assert.ok(existsSync(join(repo, "feature.txt")), "merged file present at repoRoot");
    assert.equal(readFileSync(join(repo, "feature.txt"), "utf8"), "generated by agent\n");
    // Base tree has no *tracked* modifications after a --no-ff merge commit (the
    // untracked .pi/worktrees checkout under repoRoot is a benign isolation artifact).
    assert.equal(gitOut("status", "--porcelain", "--untracked-files=no").trim(), "", "base tree clean after merge");
  } finally {
    rmSync(repo, { recursive: true, force: true });
  }
});

test("commitWorktree returns false when the worktree has no changes and base stays put", async () => {
  const { repo, gitOut } = setupRepo("pi-saga-empty-");
  try {
    const wt = await createWorktree(repo, "run-2-0-noop");
    assert.equal(wt.isolated, true);

    const headBefore = gitOut("rev-parse", "HEAD").trim();

    const committed = await commitWorktree(wt, "nothing to do");
    assert.equal(committed, false, "no changes → no commit");

    // Merging an unchanged branch must not advance or dirty the base branch.
    await mergeWorktree(wt);
    assert.equal(gitOut("rev-parse", "HEAD").trim(), headBefore, "base HEAD unchanged");
    assert.equal(readFileSync(join(repo, "file.txt"), "utf8"), "base\n", "base file unchanged");
    assert.equal(gitOut("status", "--porcelain", "--untracked-files=no").trim(), "", "base tree clean");
  } finally {
    rmSync(repo, { recursive: true, force: true });
  }
});

test("mergeWorktree reports a conflict, aborts, and leaves the base clean with the branch intact", async () => {
  const { repo, git, gitOut } = setupRepo("pi-saga-conflict-");
  try {
    const wt = await createWorktree(repo, "run-3-0-clash");
    assert.equal(wt.isolated, true);
    assert.ok(wt.branch, "branch created");

    // Worktree branch changes line 1 one way and commits via the function under test.
    writeFileSync(join(wt.cwd, "file.txt"), "worktree change\n");
    assert.equal(await commitWorktree(wt, "pi/wf clash"), true);

    // Base branch changes the SAME line differently, so the histories diverge and
    // a 3-way merge cannot fast-forward — it must conflict on file.txt.
    writeFileSync(join(repo, "file.txt"), "base change\n");
    git("add", ".");
    git("commit", "-q", "-m", "base divergent");

    const result = await mergeWorktree(wt);
    assert.deepEqual(result, { merged: false, conflict: true });

    // Merge was aborted: no unmerged/tracked changes remain (ignore the .pi worktree dir).
    assert.equal(gitOut("status", "--porcelain", "--untracked-files=no").trim(), "", "base tree clean after abort");
    assert.equal(readFileSync(join(repo, "file.txt"), "utf8"), "base change\n", "base kept its own version");
    assert.ok(!readFileSync(join(repo, "file.txt"), "utf8").includes("<<<<<<<"), "no conflict markers");

    // The branch survives for manual reconciliation.
    assert.equal(
      gitOut("branch", "--list", wt.branch ?? "")
        .trim()
        .replace(/^[*+]?\s*/, ""),
      wt.branch,
      "conflicting branch preserved",
    );
  } finally {
    rmSync(repo, { recursive: true, force: true });
  }
});

test("removeWorktree keepBranch drops the dir but preserves the branch; without it the branch is deleted", async () => {
  const { repo, gitOut } = setupRepo("pi-saga-keepbranch-");
  try {
    const wt = await createWorktree(repo, "run-4-0-keep");
    assert.equal(wt.isolated, true);
    assert.ok(wt.branch);
    // Give the branch a commit so it is a real, non-trivial branch.
    writeFileSync(join(wt.cwd, "note.txt"), "work\n");
    assert.equal(await commitWorktree(wt, "pi/wf keep"), true);

    await removeWorktree(wt, { keepBranch: true });
    assert.ok(!existsSync(wt.cwd), "worktree dir removed");
    assert.equal(
      gitOut("branch", "--list", wt.branch ?? "")
        .trim()
        .replace(/^[*+]?\s*/, ""),
      wt.branch,
      "branch preserved with keepBranch",
    );

    await removeWorktree(wt);
    assert.equal(gitOut("branch", "--list", wt.branch ?? "").trim(), "", "branch deleted without keepBranch");
  } finally {
    rmSync(repo, { recursive: true, force: true });
  }
});

test("commitWorktree and mergeWorktree are safe no-ops on a non-isolated worktree", async () => {
  const dir = mkdtempSync(join(tmpdir(), "pi-saga-noniso-"));
  try {
    const wt = { isolated: false, cwd: dir };

    assert.equal(await commitWorktree(wt, "irrelevant"), false, "no commit when not isolated");
    assert.deepEqual(await mergeWorktree(wt), { merged: false, conflict: false }, "no merge when not isolated");

    // A no-op must not create a repo or mutate the plain directory.
    assert.ok(!existsSync(join(dir, ".git")), "no git repo created");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
